=== halorikkun/cflesportsid/.astro/collections/tournaments.schema.json
{
  "$ref": "#/definitions/tournaments",
  "definitions": {
    "tournaments": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "game": {
          "type": "string",
          "default": "crossfire-legends"
        },
        "region": {
          "type": "string",
          "default": "ID"
        },
        "startDate": {
          "type": "string"
        },
        "endDate": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "upcoming",
            "ongoing",
            "completed"
          ],
          "default": "upcoming"
        },
        "format": {
          "type": "string"
        },
        "teams": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        },
        "winner": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "startDate",
        "endDate",
        "format"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== halorikkun/cflesportsid/src/data/tournament/cfg-rtas-s1.json
{
  "name": "Clash for Glory: Road to All-Star S1",
  "game": "crossfire-legends",
  "region": "ID",
  "startDate": "2026-08-22",
  "endDate": "2026-08-23",
  "status": "completed",
  "format": "single-elimination",
  "teams": [
    "anv",
    "brotherhood",
    "cha-tra-mue",
    "endevour-tvj",
    "familia-nova",
    "g2c-prmx",
    "glory-solidarity",
    "howl-tvj",
    "scissor-rex",
    "solidarity",
    "team-69",
    "tvj-ghoib",
    "unclex-sederhana"
  ],
  "winner": "cha-tra-mue"
}
